version: '3'
services:
    mercadocredito:
        ports:
            - "8080:8080"
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes: 
          - ./app:/home